#!/bin/bash
#
# Brief description of your script
# Copyright 2022 bombisa

# Was passiert jetzt?
# Das Script ist verantwortlich dass das private Repository geclont wird - d.h. es ist nur für Leute zugänglich die auch einen Token auf dieses Projekt haben
# Das Script benötigt su - da sudo auf unseren eigenen Servern von Haus aus aus ist

SUDO_ACTIVE=1
SUDO="sudo"

INSTALL_TOKEN=0

function initBase() {

  # test if sudo active || installed
  if [[ $(which sudo) == "" ]];
  then
    SUDO_ACTIVE=0
    SUDO=""
  fi

  [[ $(which git) == "" ]] && "$SUDO" apt install git

}

function loadPartarum() {

  [[ ! -d githolder ]] && mkdir gitHolder

  local oauth="https://oauth2:"

  local github="@github.com/partarum/server.partarum.download.git"

  local link="${oauth}${INSTALL_TOKEN}${github}"

  git clone "$link" gitHolder/installPartarumServer
}

function main() {

  [[ "$1" != "" ]] && INSTALL_TOKEN="$1"

  initBase

  cd /home || exit

  mkdir partarum

  cd partarum || exit

  loadPartarum

}

main "$@"