#!/bin/bash

function main() {

  mkdir -p log/update

  pwd &> updatePwd.txt
  # ausführende Pfad von wo aus gearbeitet wird == ls

  cd gitHolder || exit

  rm -rf Partarum
  rm -rf userRep

  git clone https://github.com/partarum/partarum.git Partarum

  git clone "$(cat ../userRepURL.txt)" userRep

  rsync -anvP Partarum/ userRep &> ../log/update/rsync.txt

  cd userRep || exit

  git config user.name "Partarum"
  git config user.email "email@partarum.de"

  git status &> ../../log/update/statusBeforeAdd.txt

  git add -u

  git commit -m "updatePartarum"

  git push origin main &> ../../log/update/push.txt

  git status &> ../../log/update/statusAfterPush.txt

}

main "$@"
