#!/bin/bash

function main() {

  mkdir -p log/update

  pwd &> updatePwd.txt
  # ausführende Pfad von wo aus gearbeitet wird == ls

  cd gitHolder || exit

  rm -rf Partarum
  rm -rf userRep

  git clone https://github.com/partarum/partarum.git Partarum

  git clone "$(cat ../userRepURL.txt)" userRep

  rsync -a Partarum userRep &> ../log/update/rsync.txt

}

main "$@"
