#!/bin/bash

function main() {

  mkdir -p log/update

  pwd &> updatePwd.txt
  # ausführende Pfad von wo aus gearbeitet wird == ls

  cd gitHolder || exit

  rm -rf Partarum
  rm -rf userRep

  git clone "$(cat ../userRepURL.txt)" userRep

  git clone https://github.com/partarum/partarum.git Partarum

  cd Partarum || exit

  local commitID="$(git rev-parse HEAD)"

  mkdir -p ../../log/update/"$commitID"

  git show --stat --oneline "$(git rev-parse HEAD)" | grep "|" &> ../showDiffGrep.txt

  local splitString=""

  local line=""

  local changedFiles=()

  local dirnameOfSplitString=""

  while IFS= read -r line;
  do
    echo "$line"

    splitString=$(echo "$line" | cut -d"|" -f1 | xargs)

    changedFiles+=("$splitString")

    dirnameOfSplitString=$(dirname "$splitString")

    mkdir -p ../../log/update/"$commitID"/"$dirnameOfSplitString"

    cp -r "$splitString" ../../log/update/"$commitID"/"$splitString"

    cp "$splitString" ../userRep/"$splitString"

  done < ../showDiffGrep.txt

  git diff --name-only HEAD &> ../showDiffHead.txt

  git diff "$(git rev-parse HEAD)" &> ../showDiffCommit.txt

  cd ..

  cd userRep || exit

  git config user.name "Partarum"
  git config user.email "email@partarum.de"

  git status &> ../../log/update/statusBeforeAdd.txt

  git add -u

  git commit -m "updatePartarum-$commitID"

  git push origin main &> ../../log/update/push.txt

  git status &> ../../log/update/statusAfterPush.txt

  cd ..

  rm -rf Partarum
  rm -rf userRep

}

main "$@"
